name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Package and deploy to GitHub PR
      env:
        ORG_GRADLE_PROJECT_ghUsername: ${{ secrets.ORG_GRADLE_PROJECT_ghUsername }}
        ORG_GRADLE_PROJECT_ghToken: ${{ secrets.ORG_GRADLE_PROJECT_ghToken }}
      run: ./gradlew publish
